import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";

export default function Home({ data, dataCard }) {
  return (
    <div className="">
      <Head>
        <title>AirBNB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {data?.map((el) => (
              <SmallCard
                key={el.img}
                distance={el.distance}
                location={el.location}
                img={el.img}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            
            {dataCard?.map((el) => (
              <MediumCard key={el.img} img={el.img} title={el.title} />
            ))}
          </div>
        </section>
        <LargeCard img='https://links.papareact.com/4cj' title='The Greatests Outdoors' description='Whishlists curated by airbnb' buttonText='Get Inspired'/>
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G");
  const data = await exploreData.json();

  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT");
  const dataCard = await cardsData.json();

  return {
    props: {
      data,
      dataCard,
    },
  };
}
